releases:
  - name: create-databases-for-devops-tools
    namespace: devops
    chart: ./create-databases-for-devops-tools
    values:
      - postgres:
          host: {{ requiredEnv "DEVOPS_POSTGRES_HOST" }}
          user: {{ requiredEnv "DEVOPS_POSTGRES_USER" }}
          password: {{ requiredEnv "DEVOPS_POSTGRES_PASSWORD" }}

  - name: keycloak
    namespace: devops
    # https://github.com/kubernetes/charts/tree/master/incubator/keycloak
    chart: incubator/keycloak
    values:
      - keycloak:
          ingress:
            enabled: true
            path: /auth
            hosts:
              - keycloak.{{ env "DEVOPS_DOMAIN" }}
          persistence:
            deployPostgres: false
            dbVendor: POSTGRES
            dbHost: {{ env "DEVOPS_POSTGRES_HOST" }}

  - name: atlassian-jira-software
    namespace: devops
    chart: ./atlassian-jira-software
    values:
      - ingress:
          enabled: true
          hosts:
            - jira.{{ env "DEVOPS_DOMAIN" }}
        jira:
          reverseProxyHost: jira.{{ env "DEVOPS_DOMAIN" }}
          # Disable websudo for SAML or OIDC
          javaOptions: "-Djira.websudo.is.disabled=true"

  - name: atlassian-confluence
    namespace: devops
    chart: ./atlassian-confluence
    values:
      - ingress:
          enabled: true
          hosts:
            - confluence.{{ env "DEVOPS_DOMAIN" }}
        jira:
          reverseProxyHost: confluence.{{ env "DEVOPS_DOMAIN" }}
