releases:
  - name: keycloak
    namespace: devops
    # https://github.com/kubernetes/charts/tree/master/stable/keycloak
    chart: stable/keycloak
    values:
      - keycloak:
          ingress:
            enabled: true
            path: /auth
            hosts:
              - keycloak.{{ requiredEnv "DEVOPS_DOMAIN" }}
          persistence:
            deployPostgres: false
            dbVendor: POSTGRES
            dbHost: {{ requiredEnv "DEVOPS_POSTGRES_HOST" }}
            dbUser: keycloak
            dbPassword: keycloak

  - name: atlassian-jira-software
    namespace: devops
    chart: ./atlassian-jira-software
    values:
      - ingress:
          enabled: true
          hosts:
            - jira.{{ requiredEnv "DEVOPS_DOMAIN" }}
        jira:
          reverseProxyHost: jira.{{ requiredEnv "DEVOPS_DOMAIN" }}
          # Disable websudo for SAML or OIDC
          javaOptions: "-Djira.websudo.is.disabled=true"
        resources:
          limits:
            # for single core CPU
            cpu: 800m
            memory: 1600Mi
          requests:
            cpu: 0
            memory: 1600Mi

  - name: atlassian-confluence
    namespace: devops
    chart: ./atlassian-confluence
    values:
      - ingress:
          enabled: true
          hosts:
            - confluence.{{ requiredEnv "DEVOPS_DOMAIN" }}
        confluence:
          reverseProxyHost: confluence.{{ requiredEnv "DEVOPS_DOMAIN" }}
        resources:
          limits:
            # for single core CPU
            cpu: 800m
            memory: 1800Mi
          requests:
            cpu: 0
            memory: 1800Mi

