apiVersion: batch/v1
kind: Job
metadata:
  name: create-databases
  namespace: devops
spec:
  template:
    metadata:
      name: create-databases
      namespace: devops
    spec:
      containers:
      - name: psql
        image: postgres:9
        command: ["psql", "--file=/config/sql"]
        env:
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: host
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: admin_user
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: admin_password
        - name: PGDATABASE
          value: postgres
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: create-databases
      restartPolicy: Never
  backoffLimit: 4
