# Default values for gitbucket.

image:
  repository: int128/gitbucket
  tag: latest
  # pullPolicy: IfNotPresent

# External database:
# MySQL or PostgreSQL is strongly recommended.
# Default to H2.
# https://github.com/gitbucket/gitbucket/wiki/External-database-configuration
externalDatabase:
  url: ""
  user: ""
  password: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - gitbucket.example.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# GitBucket requires a Persisvent Volume to store data.
persistentVolume:
  ## Name of the Existing Persistent Volume Claim.
  ## If defined, PVC must be created manually before volume will be bound.
  existingClaim:

  ## Persistent volume size.
  ## This must be set for dynamic provisioning.
  size: 10Gi

  #storageClass:
  #annotations: {}
  accessModes:
    - ReadWriteOnce

replicaCount: 1

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
