# https://hub.docker.com/r/atlassian/confluence-server

image:
  repository: atlassian/confluence-server
  tag: 6.9.0
  pullPolicy: IfNotPresent

confluence:
  reverseProxyHost: confluence.example.com
  reverseProxyPort: 443
  reverseProxyScheme: https
  javaHeapSize: 1024m
  javaOptions: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - confluence.example.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  # existingClaim: existing-pvc

resources:
  # Limit CPU to prevent that the Confluence takes whole CPU and other pods die.
  limits:
    cpu: 800m
    memory: 1536Mi
  requests:
    cpu: 0
    memory: 1536Mi

nodeSelector: {}

tolerations: []

affinity: {}
