ingress:
  enabled: true
  hosts:
    - jira.example.com

proxy:
  name: jira.example.com
  port: 443
  scheme: https

jiraOptions:
  # Disable websudo for SAML or OpenID Connect authentication
  - "jira.websudo.is.disabled=true"

persistentVolume:
  existingClaim: jira
