apiVersion: v1
kind: Secret
metadata:
  name: {{ template "create-databases-for-devops-tools.fullname" . }}
  labels:
    app: {{ template "create-databases-for-devops-tools.name" . }}
    chart: {{ template "create-databases-for-devops-tools.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  postgresPassword: {{ .Values.postgres.password | b64enc | quote }}
