apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: atlassian-jira-software
  namespace: devops
  labels:
    app: atlassian-jira-software
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: atlassian-jira-software
    spec:
      initContainers:
        - name: chown-data-volume
          image: alpine
          command: ["chown", "daemon:daemon", "-R", "/var/atlassian/jira"]
          volumeMounts:
          - name: data-volume
            mountPath: /var/atlassian/jira
      containers:
        - name: atlassian-jira-software
          image: cptactionhank/atlassian-jira-software:7.9.0
          env:
            - name: X_PROXY_NAME
              valueFrom:
                configMapKeyRef:
                  name: atlassian-jira-software
                  key: host
            - name: X_PROXY_PORT
              valueFrom:
                configMapKeyRef:
                  name: atlassian-jira-software
                  key: port
            - name: X_PROXY_SCHEME
              valueFrom:
                configMapKeyRef:
                  name: atlassian-jira-software
                  key: scheme
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: atlassian-jira-software
                  key: java-opts
              value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap ${ATLASSIAN_JIRA_JAVA_OPTS}
          volumeMounts:
            - name: data-volume
              mountPath: /var/atlassian/jira
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            limits:
              cpu: 800m
              memory: 2Gi
            requests:
              memory: 2Gi
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: atlassian-jira-software
