apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlassian-jira-software
  namespace: devops
  labels:
    app: atlassian-jira-software
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
